In [ ]:
import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow import keras
from matplotlib import pyplot as plt
from sklearn import preprocessing
%matplotlib inline

In [ ]:
!git clone 'https://github.com/sachinkavindaa/Machine-learning-with-Python'

Cloning into 'Machine-learning-with-Python'...
remote: Enumerating objects: 77, done.
remote: Counting objects: 100% (77/77), done.
remote: Compressing objects: 100% (46/46), done.
remote: Total 77 (delta 18), reused 71 (delta 12), pack-reused 0
Unpacking objects: 100% (77/77), done.


In [ ]:
df = pd.read_csv('/content/Machine-learning-with-Python/ML/Weather/Weather_3/Weather.csv')
df.head()

Date  T_Max  T_Min  Wind  ...  Humidity  Precip  Pressure        Weather
0  1/1/2010     30     22     7  ...        69     0.0      1011          Sunny
1  1/2/2009     30     22     7  ...        68     0.0      1012          Sunny
2  1/3/2009     30     22     7  ...        68     0.0      1012          Sunny
3  1/4/2009     31     22     7  ...        73     0.0      1011          Sunny
4  1/5/2009     30     23     7  ...        76     0.4      1010  Partly couldy

[5 rows x 9 columns]

In [ ]:
merged = df[['T_Max', 'T_Min', 'Wind', 'Could','Precip','Humidity','Pressure']]
merged.head()

T_Max  T_Min  Wind  Could  Precip  Humidity  Pressure
0     30     22     7      4     0.0        69      1011
1     30     22     7      3     0.0        68      1012
2     30     22     7      1     0.0        68      1012
3     31     22     7      8     0.0        73      1011
4     30     23     7     29     0.4        76      1010

In [ ]:
def min_max_scaling(merged):
    # copy the dataframe
    df_norm = merged.copy()
    # apply min-max scaling
    for column in df_norm.columns:
        df_norm[column] = (df_norm[column] - df_norm[column].min()) / (df_norm[column].max() - df_norm[column].min())
        
    return df_norm
    
# call the min_max_scaling function
df_scaled = min_max_scaling(merged)

df_scaled

T_Max     T_Min      Wind     Could    Precip  Humidity  Pressure
0     0.88  0.004425  0.190476  0.031915  0.000000  0.178571  0.996714
1     0.88  0.004425  0.190476  0.021277  0.000000  0.142857  0.997809
2     0.88  0.004425  0.190476  0.000000  0.000000  0.142857  0.997809
3     0.92  0.004425  0.190476  0.074468  0.000000  0.321429  0.996714
4     0.88  0.008850  0.190476  0.297872  0.035088  0.428571  0.995619
..     ...       ...       ...       ...       ...       ...       ...
360   0.84  0.008850  0.095238  0.500000  0.000000  0.785714  0.996714
361   0.84  0.013274  0.095238  0.574468  0.000000  0.785714  0.996714
362   0.84  1.000000  0.190476  0.531915  0.008772  0.750000  0.996714
363   0.84  0.008850  0.047619  0.712766  0.219298  0.821429  0.996714
364   0.88  0.008850  0.047619  0.170213  0.061404  0.607143  0.995619

[365 rows x 7 columns]

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df_scaled[['T_Max', 'T_Min', 'Wind', 'Could','Humidity','Pressure']],df_scaled.Precip,test_size =0.2,random_state=25)

In [ ]:
X_train_scaled = X_train.copy()
X_train_scaled[['T_Max', 'T_Min', 'Wind', 'Could','Humidity','Pressure']]= X_train_scaled[['T_Max', 'T_Min', 'Wind', 'Could','Humidity','Pressure']]

X_test_scaled = X_test.copy()
X_test_scaled[['T_Max', 'T_Min', 'Wind', 'Could','Humidity','Pressure']]= X_test_scaled[['T_Max', 'T_Min', 'Wind', 'Could','Humidity','Pressure']]
_

T_Max     T_Min      Wind     Could    Precip  Humidity  Pressure
0     0.88  0.004425  0.190476  0.031915  0.000000  0.178571  0.996714
1     0.88  0.004425  0.190476  0.021277  0.000000  0.142857  0.997809
2     0.88  0.004425  0.190476  0.000000  0.000000  0.142857  0.997809
3     0.92  0.004425  0.190476  0.074468  0.000000  0.321429  0.996714
4     0.88  0.008850  0.190476  0.297872  0.035088  0.428571  0.995619
..     ...       ...       ...       ...       ...       ...       ...
360   0.84  0.008850  0.095238  0.500000  0.000000  0.785714  0.996714
361   0.84  0.013274  0.095238  0.574468  0.000000  0.785714  0.996714
362   0.84  1.000000  0.190476  0.531915  0.008772  0.750000  0.996714
363   0.84  0.008850  0.047619  0.712766  0.219298  0.821429  0.996714
364   0.88  0.008850  0.047619  0.170213  0.061404  0.607143  0.995619

[365 rows x 7 columns]

In [ ]:
model = keras.Sequential([
    keras.layers.Dense(1, input_shape=(6,), activation='sigmoid', kernel_initializer='ones', bias_initializer='zeros')
])

model.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=['accuracy'])

model.fit(X_train_scaled, y_train, epochs=5000)


Streaming output truncated to the last 5000 lines.
Epoch 2501/5000
10/10 [==============================] - 0s 2ms/step - loss: 0.2322 - accuracy: 0.3870
Epoch 2502/5000
10/10 [==============================] - 0s 2ms/step - loss: 0.2322 - accuracy: 0.3870
Epoch 2503/5000
10/10 [==============================] - 0s 2ms/step - loss: 0.2322 - accuracy: 0.3870
Epoch 2504/5000
10/10 [==============================] - 0s 2ms/step - loss: 0.2322 - accuracy: 0.3870
Epoch 2505/5000
10/10 [==============================] - 0s 2ms/step - loss: 0.2322 - accuracy: 0.3870
Epoch 2506/5000
10/10 [==============================] - 0s 2ms/step - loss: 0.2322 - accuracy: 0.3870
Epoch 2507/5000
10/10 [==============================] - 0s 2ms/step - loss: 0.2322 - accuracy: 0.3870
Epoch 2508/5000
10/10 [==============================] - 0s 2ms/step - loss: 0.2322 - accuracy: 0.3870
Epoch 2509/5000
10/10 [==============================] - 0s 2ms/step - loss: 0.2322 - accuracy: 0.3870
Epoch 2510/5000
10/10 

In [37]:
model.evaluate(X_test_scaled,y_test)


3/3 [==============================] - 0s 3ms/step - loss: 0.2230 - accuracy: 0.3425


[0.22300051152706146, 0.34246575832366943]

In [78]:
model.predict(X_test_scaled)

array([[0.04957002],
       [0.05254629],
       [0.00469068],
       [0.10013524],
       [0.01674449],
       [0.02367702],
       [0.14425734],
       [0.00580499],
       [0.05371803],
       [0.09144768],
       [0.03598604],
       [0.06649581],
       [0.0114575 ],
       [0.23605534],
       [0.03250006],
       [0.18807954],
       [0.11800408],
       [0.01349312],
       [0.07132959],
       [0.3087762 ],
       [0.16060838],
       [0.04665217],
       [0.03345492],
       [0.05301407],
       [0.05732772],
       [0.05973014],
       [0.01585883],
       [0.16824257],
       [0.08014712],
       [0.04070133],
       [0.05780625],
       [0.04135618],
       [0.0421693 ],
       [0.01828408],
       [0.02566561],
       [0.02124366],
       [0.05524623],
       [0.1340566 ],
       [0.01341742],
       [0.19331634],
       [0.0069229 ],
       [0.01758724],
       [0.11160836],
       [0.03947064],
       [0.04718924],
       [0.11789805],
       [0.08970687],
       [0.034

In [58]:

def sigmoid_numpy(X):
   return 1/(1+np.exp(-X))

sigmoid_numpy(np.array([12,0,1,6,3,9]))

array([0.99999386, 0.5       , 0.73105858, 0.99752738, 0.95257413,
       0.99987661])

In [69]:
def log_loss(y_true, y_predicted):
    epsilon = 1e-15
    y_predicted_new = [max(i,epsilon) for i in y_predicted]
    y_predicted_new = [min(i,1-epsilon) for i in y_predicted_new]
    y_predicted_new = np.array(y_predicted_new)
    return -np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))

In [72]:
class myNN:
    def __init__(self):
        self.w1 = 1 
        self.w2 = 1
        self.w3 = 1
        self.w4 = 1
        self.w5 = 1
        self.w6 = 1
        self.bias = 0
        
    def fit(self, X, y, epochs, loss_thresold):
         self.w1, self.w2, self.w3, self.w4, self.w5, self.w6, self.bias = self.gradient_descent(X['T_Max'],X['T_Min'],X['Wind'],X['Could'],X['Humidity'],
                                                                                                 X['Pressure'],y, epochs, loss_thresold)
         
         print(f"Final weights and bias: w1: {self.w1}, w2: {self.w2}, w3: {self.w3}, w4: {self.w4},  w5: {self.w5}, w6: {self.w6} , bias: {self.bias}")
        
    def predict(self, X_test):
        weighted_sum = self.w1*X_test['T_Max'] + self.w2*X_test['T_Min'] + self.w3*X_test['Wind'] + self.w4*X_test['Could']+self.w5*X_test['Humidity']
        + self.w6*X_test['Pressure'] + self.bias
        return sigmoid_numpy(weighted_sum)

    def gradient_descent(self, T_Max, T_Min, Wind, Could, Pressure, Humidity, y_true, epochs, loss_thresold):
        w1 = w2= w3 =w4 = w5 = w6 = 1
        bias = 0
        rate = 0.5
        n = len(Wind)
        for i in range(epochs):
            weighted_sum = w1 * T_Max + w2* T_Min + w3* Wind + w4* Could + w5* Pressure + w6* Humidity + bias
            y_predicted = sigmoid_numpy(weighted_sum)
            loss = log_loss(y_true, y_predicted)
            
            w1d = (1/n)*np.dot(np.transpose(T_Max),(y_predicted-y_true)) 
            w2d = (1/n)*np.dot(np.transpose(T_Min),(y_predicted-y_true)) 
            w3d = (1/n)*np.dot(np.transpose(Wind),(y_predicted-y_true)) 
            w4d = (1/n)*np.dot(np.transpose(Could),(y_predicted-y_true)) 
            w5d = (1/n)*np.dot(np.transpose(Pressure),(y_predicted-y_true)) 
            w6d = (1/n)*np.dot(np.transpose(Humidity),(y_predicted-y_true)) 

            bias_d = np.mean(y_predicted-y_true)
            w1 = w1 - rate * w1d
            w2 = w2 - rate * w2d
            w3 = w3 - rate * w3d
            w4 = w4 - rate * w4d
            w5 = w5 - rate * w5d
            w6 = w6 - rate * w6d   

            
            bias = bias - rate * bias_d
            
            if i%50==0:
                print (f'Epoch:{i}, w1:{w1}, w2:{w2}, w3:{w3}, w4:{w4}, w5:{w5}, w6:{w6} , bias:{bias}, loss:{loss}')
            
           
                
        return w1, w2, w3, w4, w5, w6, bias 

In [73]:
customModel = myNN()
customModel.fit(X_train_scaled, y_train, epochs=8000, loss_thresold=0.9631)


Epoch:0, w1:0.6256206608955643, w2:0.9930658194514242, w3:0.8000018456186203, w4:0.8245307508110578, w5:0.7170731852217438, w6:0.5588715607274022 , bias:-0.44441585799148436, loss:3.119090292254781
Epoch:50, w1:-0.4852454601915174, w2:0.9728652292439302, w3:0.06903062895215677, w4:0.4625433104595314, w5:0.10947521753047353, w6:-0.700930043359963 , bias:-1.7221259448844812, loss:0.2567041381654656
Epoch:100, w1:-0.5571765881736089, w2:0.9723224167092482, w3:-0.07416446880177481, w4:0.6071102518792135, w5:0.3031002726493361, w6:-0.7306795911776671 , bias:-1.7613349307242714, loss:0.2532339553285908
Epoch:150, w1:-0.6237647889605763, w2:0.9718095535714542, w3:-0.20641084420244626, w4:0.7389011864371607, w5:0.4822659577624169, w6:-0.7582199281916636 , bias:-1.798226020390733, loss:0.2502847136603644
Epoch:200, w1:-0.6858670418678168, w2:0.9713259181606535, w3:-0.32838974023923617, w4:0.8590442358696918, w5:0.6481358409799481, w6:-0.784222298779772 , bias:-1.8334638993742889, loss:0.2477733

In [76]:
customModel.predict(X_test_scaled)



364    0.861017
225    0.868739
33     0.276442
100    0.932644
45     0.613148
         ...   
149    0.949807
192    0.601052
287    0.877113
168    0.924389
341    0.973849
Length: 73, dtype: float64

In [77]:
model.predict(X_test_scaled)



array([[0.04957002],
       [0.05254629],
       [0.00469068],
       [0.10013524],
       [0.01674449],
       [0.02367702],
       [0.14425734],
       [0.00580499],
       [0.05371803],
       [0.09144768],
       [0.03598604],
       [0.06649581],
       [0.0114575 ],
       [0.23605534],
       [0.03250006],
       [0.18807954],
       [0.11800408],
       [0.01349312],
       [0.07132959],
       [0.3087762 ],
       [0.16060838],
       [0.04665217],
       [0.03345492],
       [0.05301407],
       [0.05732772],
       [0.05973014],
       [0.01585883],
       [0.16824257],
       [0.08014712],
       [0.04070133],
       [0.05780625],
       [0.04135618],
       [0.0421693 ],
       [0.01828408],
       [0.02566561],
       [0.02124366],
       [0.05524623],
       [0.1340566 ],
       [0.01341742],
       [0.19331634],
       [0.0069229 ],
       [0.01758724],
       [0.11160836],
       [0.03947064],
       [0.04718924],
       [0.11789805],
       [0.08970687],
       [0.034